// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh3ZvdGAd0TV4SQRhD-l5nPNEUpP8Ebzc',
    appId: '1:860037516705:web:e806c54ae15b563f9dcfe0',
    messagingSenderId: '860037516705',
    projectId: 'marine-biodiversity',
    authDomain: 'marine-biodiversity.firebaseapp.com',
    storageBucket: 'marine-biodiversity.firebasestorage.app',
    measurementId: 'G-PPYF4HH1TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh3o-K0IR-XlfGPzaBfHBMXl7YFeM7-Fo',
    appId: '1:860037516705:android:d3b1ac544b0d18619dcfe0',
    messagingSenderId: '860037516705',
    projectId: 'marine-biodiversity',
    storageBucket: 'marine-biodiversity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeSK0qUPfDXF3oBdDoIvxQ9iU9fnB_bto',
    appId: '1:860037516705:ios:445e8d4eca7d7f7a9dcfe0',
    messagingSenderId: '860037516705',
    projectId: 'marine-biodiversity',
    storageBucket: 'marine-biodiversity.firebasestorage.app',
    iosBundleId: 'com.skiez.marineTrust',
  );
}
